Build the test (assignment 2)
WentaoZhan1998/hiperglm pull request #1
Opened 2023-02-22 16:03 UTC by WentaoZhan1998

This pull request is a part of assignment 2.

2023-02-24 19:56 UTC, chinandrew requested changes
-0 For EX1.
-0 For EX2A.
-0 For EX2B, though was confused since it wasnt in the Rmd file.

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
>  #' @return A list including the information of the fitted model
you'll need to update your documentation since you added an argument

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
> +  #hglm_out$XtX_inv = XtX_inv
-1

Don't leave unnecessary comments in. If you need to get old code, use your git history.

2023-02-24 19:56 UTC, chinandrew commented on R/model_output.R
> +  print(hglm_out$coefficients)
Keep things simple and just have `coef` return `hglm_out$coefficients`. No printing needed

2023-02-24 19:56 UTC, chinandrew commented on tests/testthat/test-are-all-close.R
> +  x = rep(1, 100)
You don't really need 100 length vectors, but this is fine.

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
>    supported_model <- c("linear", "logit")
```suggestion
  supported_model <- c("linear")
```

You can also try using something like `match.arg()` here

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
>    int = F
-1

don't overengineer for now, keep things simple. And for design matrix validation I'd split this out into it's own function, see related comment below

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
> +    }
-5

Break the solves out into their own functions, e.g.

```
 if(option["mle_solver"] == "BFGS"){
    model_coefs = mle_bfgs(...)
    } else {
    model_coefs = mle_pinv(...)
    }
```

Functions should be simple and only do one thing. In this case hiper_glm is just orchestrating the right function to call, and if you change how pinv works (e.g. going from LU to cholesky), hiper_glm never has to know (and shouldn't have to know)

Similarly, break out log likelihood into it's own function like you did with gradient. See comment on line 9 of test-mle-finder.R for related note on this.

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
>      warning("`hiper_glm` for logit is yet to be implemented.")
-1

This is redundant with the supported_model logic on line 33

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
>    if (model == 'linear'){
Don't mix single and double quotes. Tidyverse style guide recommends double quotes. Same elsewhere in code.

2023-02-24 19:56 UTC, chinandrew commented on tests/testthat/test-are-all-close.R
> +test_that("Vectors are all close", {
try to have the filename match the function or file its testing, so are_all_close and not are-all-close

2023-02-24 19:56 UTC, chinandrew commented on tests/testthat/test-mle-finder.R
> +    coef(via_linalg_out), coef(via_bfgs_out), abs_tol = 1e-2, rel_tol = 1e-2
This tolerances seem a little loose, you should be able to bring these down if you wanted

2023-02-24 19:56 UTC, chinandrew commented on tests/testthat/test-mle-finder.R
> +beta = rnorm(ncol(design))
-1 

Don't use randomness if you don't have to. Specifying a hardcoded `beta` works fine here and then the values are easy to know/read

If you do want to use it, e.g. to try a bunch of configurations, always use a seed as you have done.

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
> +#' @param beta vector, the potent8ial
```suggestion
#' @param beta vector, the potential
```

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
> +    if(is.null(option$mle_solver)){
If you're going to let people specify BFGS and the default is pseudo inv, I'd recommend also letting them specify pseudo inv explicitely. It's a bit weird if the default is not an explicitely specifiable option.

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
> +    else if(option$mle_solver == 'BFGS'){
-1 

missing an `else` after the `else if`

2023-02-24 19:56 UTC, chinandrew commented on tests/testthat/test-mle-finder.R
> +  log_lkl = function(beta, noise_var = 1){
As mentioned above, having log_lkl broken out would prevent you from having to write this twice (and if you change it in the main body of the code, you no longer are testing it properly here if you forgot to also change it here.

2023-02-24 19:56 UTC, chinandrew commented on R/hiper_glm.R
> +       .5*crossprod(outcome - crossprod(t(design), beta))[1,1]/noise_var
Be consistent with spacing between operators, e.g. `1 + 2 * 4` and not `1+2 * 4`. You can use an auto-formatter do handle this for you.

2023-03-06 04:08 UTC, merged

2023-03-06 04:36 UTC, WentaoZhan1998 commented on R/hiper_glm.R
> +  #hglm_out$XtX_inv = XtX_inv
Hi Andrew, I missed a typo in the pseudo-inverse part when I merged this pull request. So I made a follow-up one and you can go to here (https://github.com/WentaoZhan1998/hiperglm/pull/2) to see the changes.

2023-03-06 14:47 UTC, chinandrew commented on R/hiper_glm.R
> +  #hglm_out$XtX_inv = XtX_inv
Thanks for the note, you can go ahead and merge that one too.

2023-03-06 14:50 UTC, chinandrew commented on R/hiper_glm.R
> +    if (option$mle_solver == "pinv") {
if you wanted to add a default  option, you could do add a `|is.null(option$mlesolver )` to this condition

2023-03-06 14:51 UTC, chinandrew commented on R/hiper_glm.R
> +    if (option$mle_solver == "pinv") {
Similarly you may want to add error handling if a non-valid solver is supploed

2023-03-06 16:05 UTC, chinandrew commented
Final grade 100/100

-0 For EX1.
-0 For EX2A.
-0 For EX2B, though was confused since it wasnt in the Rmd file.
-0 For EX3.